[package]
name = "tuack-ng"
version = "0.0.1"
edition = "2024"

[dependencies]
bytes = "1.11.0"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["cargo", "derive"] }
clap-i18n-richformatter = { version = "0.3.0", features = ["derive"] }
colored = "3.0.0"
log = "0.4.29"
log4rs = "1.4.0"
markdown-ppp = { path = "./markdown-ppp", features = ["parser", "ast-serde", "ast-transform", "typst-printer"] }
nom = "8.0.0"
pretty = "0.12.5"
serde = "1.0.228"
serde_json = "1.0.145"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
